# Generated by Django 3.2.6 on 2022-03-19 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('no', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('Student_ID', models.CharField(max_length=200, null=True)),
                ('Student_password', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
