# Generated by Django 3.2.9 on 2022-03-28 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stu',
            fields=[
                ('step', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
            ],
        ),
    ]
