# Generated by Django 3.2.9 on 2022-03-28 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_stu'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stu',
        ),
        migrations.AddField(
            model_name='student',
            name='step',
            field=models.IntegerField(default=0),
        ),
    ]
