# Generated by Django 3.2.9 on 2022-03-27 17:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20220319_2250'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company', models.CharField(max_length=150, null=True)),
                ('Description', models.CharField(max_length=150, null=True)),
                ('Published', models.DateTimeField(default=django.utils.timezone.now)),
                ('close', models.DateTimeField(default=None)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
