# Generated by Django 3.2.9 on 2022-03-28 07:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20220328_0011'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, null=True)),
                ('sername', models.CharField(max_length=150, null=True)),
                ('studentID', models.CharField(max_length=10, null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('major', models.CharField(max_length=150, null=True)),
                ('company', models.CharField(max_length=150, null=True)),
                ('addresscompany', models.CharField(max_length=150, null=True)),
                ('destination', models.CharField(max_length=150, null=True)),
                ('phone', models.CharField(max_length=10, null=True)),
                ('email', models.CharField(max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PDFForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=150, null=True)),
                ('body', models.TextField(blank=True)),
                ('link', models.URLField(null=True)),
                ('logo', models.FileField(blank=True, null=True, upload_to='')),
                ('signature', models.FileField(blank=True, null=True, upload_to='')),
                ('address', models.CharField(max_length=150, null=True)),
                ('booknumber', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
