# Generated by Django 3.2.9 on 2022-04-02 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_form_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='nameTitle',
            field=models.CharField(choices=[('Miss', 'Miss'), ('Mrs.', 'Mrs'), ('Mr.', 'Mr')], default=None, max_length=100),
        ),
    ]
