# Generated by Django 3.2.7 on 2022-04-04 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_document_file1_history'),
        ('main', '0008_alter_form_nametitle'),
    ]

    operations = [
    ]
