# Generated by Django 3.2.9 on 2022-04-04 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_merge_20220404_1228'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.DeleteModel(
            name='File1',
        ),
        migrations.DeleteModel(
            name='History',
        ),
        migrations.RemoveField(
            model_name='pdfform',
            name='address',
        ),
        migrations.RemoveField(
            model_name='pdfform',
            name='body',
        ),
        migrations.RemoveField(
            model_name='pdfform',
            name='header',
        ),
        migrations.RemoveField(
            model_name='pdfform',
            name='link',
        ),
        migrations.RemoveField(
            model_name='pdfform',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='pdfform',
            name='signature',
        ),
    ]
