# Generated by Django 3.2.8 on 2022-04-24 16:21

from django.db import migrations, models
import main.utils
import main.validators


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documentstep5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=100)),
                ('attachment', models.FileField(null=True, upload_to=main.utils.upload_to, validators=[main.validators.validate_file_extension])),
            ],
        ),
        migrations.RenameModel(
            old_name='Document',
            new_name='Documentstep3',
        ),
    ]
