# Generated by Django 3.2.9 on 2022-04-29 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20220424_2321'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PDFForm',
        ),
        migrations.AddField(
            model_name='form',
            name='booknumber',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='form',
            name='nameTitle',
            field=models.CharField(choices=[('นางสาว', 'นางสาว'), ('นาง', 'นาง'), ('นาย', 'นาย')], default=None, max_length=100),
        ),
    ]
