# Generated by Django 3.2.9 on 2022-04-29 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20220429_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='booknumber',
            field=models.CharField(default=True, max_length=50, null=True),
        ),
    ]
